import './globals.css'
import { Roboto  } from 'next/font/google'
import Head from 'next/head';

const roboto  = Roboto({ 
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
 })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <Head>
       <title>Your-Choice</title>
       </Head>
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
